### ISSUE TITLE
IncompatibleClassChangeError on configuration attempt

### ISSUE THREAD

**Issue by PC1up** [MarcPG1905/Peelocity#1]
If I try to execute the jar file after the config was created and everything, the following exception occurs:
```
=== General - PeeUp (Peelocity Setup) ===
| An easy tool for setting up Peelocity's configuration to work
| with your server.

Press any key to continue!
Exception in thread "main" java.lang.IncompatibleClassChangeError: class com.marcpg.formular.RawConsoleInput$Msvcrt can not implement com.marcpg.peelocity.libs.Library, because it is not an interface (com.marcpg.peelocity.libs.Library is in unnamed module of loader 'app')
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at com.marcpg.formular.RawConsoleInput.initWindows(RawConsoleInput.java:118)
        at com.marcpg.formular.RawConsoleInput.readWindows(RawConsoleInput.java:89)
        at com.marcpg.formular.RawConsoleInput.read(RawConsoleInput.java:50)
        at com.marcpg.formular.CLIFormular.render(CLIFormular.java:105)
        at com.marcpg.peelocity.PeeUp.main(PeeUp.java:96)
```
Velocity Version: 3.3.0
Plugin Version: 1.0.2 Build 1

SignedVelocity is installed on proxy and sub server.

**Comment by MarcPG1905** [comment]
Thanks for addressing this issue!

I found the issue and I'm working on a fix right now. Seems like it was an issue regarding the Gradle configuration. Just me not being cautious enough and overseeing an obvious issue.

**A fix will probably be uploaded in the next 5 or so minutes!**

**Comment by MarcPG1905** [comment]
**Fix should be out on all platforms!** Might take a few seconds to update...

Thanks for helping with this, as I probably wouldn't have noticed it!
