### ISSUE TITLE
UnsatisfiedLinkError on configuration setup

### ISSUE THREAD

**Issue by PC1up** [MarcPG1905/Peelocity#2]
Welp, same situation as the one I reported before, yet a different exception:

```
=== General - PeeUp (Peelocity Setup) ===
| An easy tool for setting up Peelocity's configuration to work
| with your server.

Press any key to continue!
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't obtain class com.sun.jna.CallbackReference
        at com.sun.jna.Native.initIDs(Native Method)
        at com.sun.jna.Native.<clinit>(Native.java:248)
        at com.marcpg.formular.RawConsoleInput.initWindows(RawConsoleInput.java:118)
        at com.marcpg.formular.RawConsoleInput.readWindows(RawConsoleInput.java:89)
        at com.marcpg.formular.RawConsoleInput.read(RawConsoleInput.java:50)
        at com.marcpg.formular.CLIFormular.render(CLIFormular.java:105)
        at com.marcpg.peelocity.PeeUp.main(PeeUp.java:96)
```
Peelocity 1.0.2 Build 2
Velocity 3.3.0

**Comment by MarcPG1905** [comment]
I'm not able to reproduce the exception.
Can you tell m what version of Windows you're running and in what environment.

The only things I can think of right now is a missing default library in your windows installation.

Maybe also try restarting the setup, to see if it solves the problem temporarily.

Very sorry for the unstable setup!

**Comment by PC1up** [comment]
Hey,
I'm running Windows 11 Home, Version 10.0.22631 Build 22631. I already tried restarting the setup, but it didn't help

**Comment by MarcPG1905** [comment]
I found the issue and fixed it. Was related to me assuming some Windows specific stuff, that turns out, isn't the same for each Windows machine.

Took a while because of some personal stuff, but the fix should be up on all platforms in a few minutes.
**Sorry for the inconvenience!**
